In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.ensemble import RandomForestClassifier

In [2]:
pima = pd.read_csv("zoo_data.csv")

In [3]:
y=pima["1.7"]
import numpy as np
y=np.array(y)
print(y)

[1 4 1 1 1 1 4 4 1 1 2 4 7 7 7 2 1 4 1 2 2 1 2 6 5 5 1 1 1 6 1 1 2 4 1 1 2
 4 6 6 2 6 2 1 1 7 1 1 1 1 6 5 7 1 1 2 2 2 2 4 4 3 1 1 1 1 1 1 1 1 2 7 4 1
 1 3 7 2 2 3 7 4 2 1 7 4 2 6 5 3 3 4 1 1 2 1 6 1 7 2]

In [4]:
x=pima.drop(columns=["1.7"])
x

    1  0  0.1  1.1  0.2  0.3  1.2  1.3  1.4  1.5  0.4  0.5  4  0.6  0.7  1.6
0   1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1
1   0  0    1    0    0    1    1    1    1    0    0    1  0    1    0    0
2   1  0    0    1    0    0    1    1    1    1    0    0  4    0    0    1
3   1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1
4   1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1
.. .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ..  ...  ...  ...
95  1  0    0    1    0    0    0    1    1    1    0    0  2    1    0    1
96  1  0    1    0    1    0    0    0    0    1    1    0  6    0    0    0
97  1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1
98  0  0    1    0    0    0    0    0    0    1    0    0  0    0    0    0
99  0  1    1    0    1    0    0    0    1    1    0    0  2    1    0    0

[100 rows x 16 columns]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(x, y)

In [6]:
clf = RandomForestClassifier()

In [7]:
clf = clf.fit(X_train,y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_test)
y_pred

array([2, 1, 2, 1, 2, 1, 1, 1, 3, 5, 2, 1, 5, 5, 4, 1, 1, 4, 2, 4, 4, 1,
       1, 1, 4], dtype=int64)

In [13]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0